version: '3'
services:

  postgres:
    container_name: pg_training
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432

  training_service:
    container_name: training_service
    build:
      context: .
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    ports:
      - 8081:8080
    volumes:
      - ./app/alembic:/app/alembic
