"""empty message

Revision ID: e6fec831e9a0
Revises: 
Create Date: 2024-07-05 19:01:22.912084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from models.exercises import MuscleGroupModel, MuscleGroup

# revision identifiers, used by Alembic.
revision: str = 'e6fec831e9a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('musclegroupmodel',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name',
                              sa.Enum('Chest', 'Upper_back', 'Lower_back', 'Abs', 'Traps', 'Shoulders', 'Biceps',
                                      'Triceps', 'Neck', 'Forearms', 'Glutes', 'Quads', 'Hamstrings', 'Calfs',
                                      'Obliques', name='musclegroup'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('name', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('exercisemusclegrouplink',
                    sa.Column('exercise_id', sa.Integer(), nullable=False),
                    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
                    sa.Column('engagement', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
                    sa.ForeignKeyConstraint(['muscle_group_id'], ['musclegroupmodel.id'], ),
                    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id')
                    )
    op.create_table('exerciseperformed',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('exercise_id', sa.Integer(), nullable=False),
                    sa.Column('sets', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
                    sa.PrimaryKeyConstraint('id', 'exercise_id')
                    )

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # create teams for each team name
    muscles = [MuscleGroupModel(name=m.name) for i, m in enumerate(MuscleGroup)]
    session.add_all(muscles)

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exerciseperformed')
    op.drop_table('exercisemusclegrouplink')
    op.drop_table('user')
    op.drop_table('musclegroupmodel')
    op.drop_table('exercise')
    # ### end Alembic commands ###
